lego_loam:

    # VLP-16
    laser:
        num_vertical_scans: 16
        num_horizontal_scans: 1800
        vertical_angle_bottom: -15          # degrees
        vertical_angle_top: 15              # degrees
        sensor_mount_angle: 0               # degrees
        scan_period: 0.1                    # seconds

    imageProjection:
        ground_scan_index: 7 
        ground_points_angle_threshold: 1 
        segment_valid_point_num: 5
        segment_valid_line_num: 3
        segment_theta: 55                       # decrese this value may improve accuracy

    featureAssociation:
        edge_threshold: 0.2
        surf_threshold: 0.1
        sharp_points: 5 
        less_sharp_points: 80 
        flat_points: 10 
        nearest_feature_search_distance: 5
        edge_iterations: 100
        surf_iterations: 100
        convergent_rotation: 0.001
        convergent_translation: 0.001

    mapping:
        enable_loop_closure: false
        mapping_frequency_divider: 5

        surrounding_keyframe_search_radius: 50.0   # key frame that is within n meters from current pose will be
                                                   # considered for scan-to-map optimization (when loop closure disabled)
        surrounding_keyframe_search_num: 50        # submap size (when loop closure enabled)

        history_keyframe_search_radius: 7.0        # key frame that is within n meters from current pose will be considerd for loop closure
        history_keyframe_search_num: 25            # 2n+1 number of history key frames will be fused into a submap for loop closure
        history_keyframe_fitness_score: 0.3        # the smaller the better alignment

        global_map_visualization_search_radius: 500.0 # key frames with in n meters will be visualized
